# Generated by Django 4.1.3 on 2022-11-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": (
                    ("view_admin_page", "Can view admin page"),
                    ("view_staff_page", "Can view staff page"),
                    ("view_editor_page", "Can view editor page"),
                    ("view_student_page", "Can view student page"),
                )
            },
        ),
    ]
